const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function ask(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer);
    });
  });
}

function generateJWTSecret() {
  return crypto.randomBytes(64).toString('hex');
}

async function main() {
  console.log('\n🎓 ===============================================');
  console.log('   SMART LEARNING - SETUP WIZARD');
  console.log('   ===============================================\n');

  console.log('Saya akan membantu Anda setup aplikasi Smart Learning.\n');

  // Step 1: JWT Secret
  console.log('📌 STEP 1: JWT Secret Key');
  console.log('   JWT Secret digunakan untuk enkripsi authentication token.\n');
  
  const useAutoJWT = await ask('   Generate JWT Secret otomatis? (Y/n): ');
  let jwtSecret;

  if (useAutoJWT.toLowerCase() === 'n') {
    jwtSecret = await ask('   Masukkan JWT Secret (min 32 karakter): ');
    if (jwtSecret.length < 32) {
      console.log('   ⚠️  JWT Secret terlalu pendek! Menggunakan auto-generate...');
      jwtSecret = generateJWTSecret();
    }
  } else {
    jwtSecret = generateJWTSecret();
    console.log('   ✅ JWT Secret berhasil di-generate!\n');
  }

  // Step 2: Port Configuration
  console.log('📌 STEP 2: Port Configuration');
  console.log('   Port untuk menjalankan aplikasi.\n');
  
  const port = await ask('   Port (tekan Enter untuk 3000): ') || '3000';
  console.log(`   ✅ Port: ${port}\n`);

  // Step 3: Database Configuration
  console.log('📌 STEP 3: Database Configuration\n');
  
  const dbHost = await ask('   Database Host (tekan Enter untuk localhost): ') || 'localhost';
  const dbPort = await ask('   Database Port (tekan Enter untuk 5432): ') || '5432';
  const dbName = await ask('   Database Name (tekan Enter untuk smart_learning): ') || 'smart_learning';
  const dbUser = await ask('   Database User (tekan Enter untuk postgres): ') || 'postgres';
  const dbPassword = await ask('   Database Password: ');

  console.log('\n   ✅ Database configuration saved!\n');

  // Step 4: Create .env.local file
  console.log('📌 STEP 4: Creating .env.local file...\n');

  const envContent = `# ==============================================
# SMART LEARNING - ENVIRONMENT VARIABLES
# Generated by setup script on ${new Date().toISOString()}
# ==============================================

# Database Configuration
DB_HOST=localhost
DB_PORT=5432
DB_NAME=smart_learning
DB_USER=postgres
DB_PASSWORD=12345

# JWT Configuration
JWT_SECRET=${jwtSecret}
JWT_EXPIRES_IN=7d

# Application Configuration
NODE_ENV=development
PORT=${port}
NEXT_PUBLIC_API_URL=http://localhost:${port}

# Optional: Uncomment untuk custom settings
# NEXT_PUBLIC_HOST=localhost
# NEXT_PUBLIC_HTTPS=false
`;

  const envPath = path.join(process.cwd(), '.env.local');
  
  try {
    fs.writeFileSync(envPath, envContent, 'utf8');
    console.log('   ✅ File .env.local berhasil dibuat!\n');
  } catch (error) {
    console.error('   ❌ Error membuat .env.local:', error.message);
    process.exit(1);
  }

  // Step 5: Summary
  console.log('📌 SETUP SUMMARY\n');
  console.log('   ✅ JWT Secret: ****** (tersimpan di .env.local)');
  console.log(`   ✅ Application Port: ${port}`);
  console.log(`   ✅ API URL: http://localhost:${port}`);
  console.log(`   ✅ Database: ${dbUser}@${dbHost}:${dbPort}/${dbName}`);
  console.log('   ✅ Environment file: .env.local\n');

  // Step 6: Next Steps
  console.log('📌 NEXT STEPS:\n');
  console.log('   1. Pastikan PostgreSQL sudah running');
  console.log('   2. Create database: CREATE DATABASE smart_learning;');
  console.log('   3. Import database schema (lihat dokumentasi)');
  console.log('   4. Install dependencies: npm install');
  console.log('   5. Run aplikasi: npm run dev');
  console.log(`   6. Buka browser: http://localhost:${port}\n`);

  // Step 7: Test Database Connection
  const testDb = await ask('   Test koneksi database sekarang? (Y/n): ');
  
  if (testDb.toLowerCase() !== 'n') {
    console.log('\n   Testing database connection...\n');
    
    try {
      const { Pool } = require('pg');
      const pool = new Pool({
        host: dbHost,
        port: parseInt(dbPort),
        database: dbName,
        user: dbUser,
        password: dbPassword,
      });

      await pool.query('SELECT NOW()');
      console.log('   ✅ Database connection successful!\n');
      await pool.end();
    } catch (error) {
      console.error('   ❌ Database connection failed:', error.message);
      console.log('   💡 Pastikan PostgreSQL running dan credentials benar.\n');
    }
  }

  console.log('🎉 Setup completed! Happy coding!\n');
  rl.close();
}

main().catch((error) => {
  console.error('Setup error:', error);
  rl.close();
  process.exit(1);
});